### ISSUE TITLE
Why use `CreateProcessAsUser` instead of `CreateProcessWithToken`?

### ISSUE THREAD

**Issue by EddieIvan01** [itm4n/PrintSpoofer#1]
Hi Clément, I have an issue after reading codes

https://github.com/itm4n/PrintSpoofer/blob/975a93c2d56fb29ccbcc7fec0ea6da141626eb7c/PrintSpoofer/PrintSpoofer.cpp#L510

Why not using `CreateProcessWithToken`? In my tesing, the LocalSystem uses `hostname$` to login in a DOMAIN environment, and `hostname$` account doesn't have `SeAssignPrimaryTokenPrivilege`

**Comment by itm4n** [comment]
At this point in the "exploit", we are impersonating the named pipe client, i.e. SYSTEM. 
It turns out you can invoke `CreateProcessAsUser` even if you don't have `SeAssignPrimaryTokenPrivilege`, as long as the identity of the token is the same as the caller's.
The caller's identity here is SYSTEM because of impersonation.
The token's identity is SYSTEM too. So that's fine.

That being said, you're totally right, I could have used `RevertToSelf` and then called `CreateProcessWithToken`. 
In this case, the caller's identity would have been LOCAL/NETWORK SERVICE and the token's identity would have been SYSTEM. But since we have `SeImpersonatePrivilege` (a prerequisite for this "exploit"). The would have worked pefectly fine.

Now, why I preferred using the `CreateProcessAsUser` trick rather than `CreateProcessWithToken`? You may ask.
The thing is, there is a weird bug with `CreateProcessWithToken`. You can't create a process in the same console. Even if you don't specify `CREATE_NEW_CONSOLE`, this API function doesn't care, it still creates a new one. So, unless you redirect stdin, stdout, ... using anonymous pipes, you cannot interact with the new process in the current console. And, I wanted to provide this feature thanks to the `-i ` option.

In you test case scenario, if the account name is `HOSTNAME$`, this probably means that you are on a Domain Controller. Anyway, this tool should still work even if SYSTEM doesn't have `SeAssignPrimaryTokenPrivilege`.

**Comment by EddieIvan01** [comment]
Thanks for the detailed answer.
The reason is the same as I guess, I also found the `CreateProcessWithToken` cannot start new process in the same console.

In my test case (Windows Server 2012 r2), the exploit cannot work. It returns `Error: 1314`, means I don't have proper privileges. It works if I replace `CreateProcessAsUser` with `CreateProcessWithToken`

![printspoofer.gif](https://i.loli.net/2020/05/13/dux5W6qsi2pz7at.gif)

**Comment by itm4n** [comment]
Ok, I see. Thank you very much for your feedback.
There's something really weird about this. I tested it on a Domain Controller, Windows Server 2016, and it worked perfectly fine, even though SYSTEM didn't have SeAssignPrimaryToken.

I'll push an update to take this case into account.

**Comment by itm4n** [comment]
I just pushed an update.
May I ask you to test again in your environment? 
If you want to pop a shell on your desktop, please use option `-d <ID>` with your session id instead of `-i`. :)

**Comment by EddieIvan01** [comment]
So quickly 👍 

Yes, it works now. Good job.
```
C:\>PrintSpoofer.exe -i -c cmd.exe
[+] Found privilege: SeImpersonatePrivilege
[+] Named pipe listening...
[!] CreateProcessAsUser() failed because of a missing privilege, retrying with CreateProcessWithTokenW().
[!] CreateProcessWithTokenW() isn't compatible with option -i

C:\>PrintSpoofer.exe -c cmd.exe
[+] Found privilege: SeImpersonatePrivilege
[+] Named pipe listening...
[!] CreateProcessAsUser() failed because of a missing privilege, retrying with CreateProcessWithTokenW().
[+] CreateProcessWithTokenW() OK
```
